(source "tromey" "http://tromey.com/elpa/")
(source gnu)
(source marmalade)
(source melpa)

(depends-on "ag")
(depends-on "auto-complete")
(depends-on "color-theme")
(depends-on "color-theme-solarized")
(depends-on "color-theme-twilight")
(depends-on "dash-at-point")
(depends-on "enh-ruby-mode")
(depends-on "expand-region")
(depends-on "feature-mode")
(depends-on "haml-mode")
(depends-on "highlight-indentation")
(depends-on "js2-mode")
(depends-on "mustache-mode")
(depends-on "pallet")
(depends-on "powerline")
(depends-on "rainbow-mode")
(depends-on "rvm")
(depends-on "soft-morning-theme")