(source "tromey" "http://tromey.com/elpa/")
(source gnu)
(source marmalade)
(source melpa)

(depends-on "auto-complete")
(depends-on "color-theme")
(depends-on "enh-ruby-mode")
(depends-on "feature-mode")
(depends-on "haml-mode")
(depends-on "highlight-indentation")
(depends-on "js2-mode")
(depends-on "pallet")
(depends-on "rvm")
(depends-on "soft-morning-theme")